name: CD - Deploy Docker App

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Execute Deployment Script
        run: |
          echo "=== DÉBUT DU DÉPLOIEMENT ==="
          cd $GITHUB_WORKSPACE
          docker-compose down
          docker-compose up -d --build
          echo "Attente du démarrage des services..."
          sleep 20
          docker ps
          echo "=== DÉPLOIEMENT TERMINÉ ==="

      - name: Health check après deploy
        run: |
          until curl -sf http://localhost:8000/; do
            echo "Waiting for backend..."
            sleep 3
          done
          echo " Backend opérationnel !"

      - name: Verify containers
        run: docker ps

      - name: Rollback si échec
        if: failure()
        run: |
          echo " Rollback en cours..."
          docker-compose down
          docker-compose up -d
          echo " Rollback terminé"

      - name: Notify Success
        if: success()
        run: echo " Déploiement réussi !"

      - name: Notify Failure
        if: failure()
        run: echo "Déploiement échoué !"