name: Security Scan - Trivy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security-scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images avant scan
        run: docker compose build

      # ✅ Trivy scan filesystem (code + dépendances)
      - name: Trivy scan - Code et dépendances
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH     # bloque si CRITICAL ou HIGH trouvé
          exit-code: 1                # ❌ pipeline échoue si vulnérabilité

      # ✅ Trivy scan image Docker
      # Scan image backend
      - name: Trivy scan - Backend
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: image
           image-ref: my-backend:latest    # ✅
           severity: CRITICAL,HIGH
           exit-code: 1

# Scan image frontend
      - name: Trivy scan - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: my-frontend:latest   # ✅
          severity: CRITICAL,HIGH
          exit-code: 1             # ❌ pipeline échoue si vulnérabilité
